# Generated by Django 3.2.7 on 2022-04-07 10:32

from django.db import migrations
from django.utils import timezone

import random
import lorem


def populate_jobs(apps, schema_editor):
    JOB_COUNT = 4

    job_types = ['LWN','SNW','PET','LND','AUT','GAR','MOV']

    User = apps.get_model('accounts', 'CustomUser')
    Job = apps.get_model('yardSite', 'Job')
    for user in User.objects.all().exclude(username='owner'):
        for i in range(JOB_COUNT):
            job = Job(
                name = f'{user.first_name} {user.last_name}',
                description = lorem.paragraph(),
                job_type = random.choice(job_types),
                cash_reward = 99,
                customer = user.customer,
                date_to_be_finished_by = timezone.now() + timezone.timedelta(days=2),
                zip_code = user.zip_code
            )
            job.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_populate_users')
    ]

    operations = [
        migrations.RunPython(populate_jobs)
    ]
