# Generated by Django 4.0.2 on 2022-03-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_to_be_finished_by',
            field=models.DateField(blank=True),
        ),
    ]
