# Generated by Django 3.2.7 on 2022-04-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yardSite', '0001_initial'),
        ('yardSite', '0002_populate_jobs'),
    ]

    operations = [
    ]
