# Generated by Django 4.0.2 on 2022-04-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardSite', '0003_merge_0001_initial_0002_populate_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cash_reward',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
