# Generated by Django 3.2.8 on 2022-04-05 02:01

from django.db import migrations


def populate_users():
    COUNT = 10

    User = apps.get_model('accounts', 'CustomUser')
    for i in range(COUNT):



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_users)
    ]
