# Generated by Django 3.2.8 on 2022-04-05 02:01

from django.db import migrations
from django.contrib.auth.hashers import make_password

import random


def populate_users(apps, schema_editor):
    USER_COUNT = 12
    areas = ['11111','22222','33333','44444']

    User = apps.get_model('accounts', 'CustomUser')
    Customer = apps.get_model('yardSite', 'Customer')
    Worker = apps.get_model('yardSite', 'Worker')
    for i in range(USER_COUNT):
        user = User(
            username = f'user-{i}',
            first_name = 'user',
            last_name = str(i),
            email = f'user{i}@example.com',
            city = 'Logan',
            state = 'UT',
            zip_code = random.choice(areas),
            address = f'street-{i}',
        )
        user.password = make_password(f'{i}'*8)
        user = user.save()

    for user in User.objects.all():
        customer = Customer(user=user)
        customer.save()
        worker = Worker(user=user)
        worker.save()
        
class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_owner'),
        ('yardSite', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_users)
    ]
